githubConfigUrl: "https://github.com/dlrkdms125/ARC-RUNNER"

githubConfigSecret:
  github_app_id: ""
  github_app_installation_id: ""
  github_app_private_key: ""

runnerScaleSetName: "arc-scale"

minRunners: 1
maxRunners: 5

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest

